import type {Metadata} from 'next'
import {Outfit} from 'next/font/google'
import '../styles/globals.css'
import {ReactNode} from "react";
import {classNames} from "@/utils/css";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";

const outfitFont = Outfit({
    weight: ['300', '500', '600'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Config Sync',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body
            className={classNames(
                outfitFont.className,
                "max-w-screen overflow-x-hidden",
            )}
        >
        <Providers>
            <NavBar/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
